"""Medical colleges and schools — merged into COLLEGES_SEED_DATA at import."""

ADDITIONAL_INSTITUTIONS_SEED = [
    # —— Medical colleges ——
    {
        "name": "All India Institute of Medical Sciences (AIIMS), New Delhi",
        "location": "New Delhi, Delhi",
        "fees": 1628,
        "rating": 4.9,
        "stream": "Medical",
        "institution_type": "College",
        "courses": "MBBS, MD General Medicine, MD Pediatrics, MS General Surgery, DM Cardiology",
        "placements_pct": 99.0,
        "package_median": 12.0,
        "package_highest": 24.0,
        "logo_url": "https://upload.wikimedia.org/wikipedia/en/thumb/8/8a/AIIMS_New_Delhi_logo.svg/240px-AIIMS_New_Delhi_logo.svg.png",
        "description": "AIIMS New Delhi is India's premier medical institute for undergraduate and postgraduate medical education, research, and patient care. Admissions are through NEET-UG and INI-CET.",
        "cutoffs": [
            {"exam": "NEET-UG", "branch": "MBBS", "category": "General", "min_rank": 1, "max_rank": 57},
            {"exam": "NEET-UG", "branch": "MBBS", "category": "OBC", "min_rank": 1, "max_rank": 150},
            {"exam": "NEET-UG", "branch": "MBBS", "category": "SC", "min_rank": 1, "max_rank": 1200},
        ],
        "reviews": [
            {"reviewer_name": "Dr. Anjali Verma", "rating": 5.0, "text": "World-class clinical exposure from year one. Residency placements at top hospitals globally."},
            {"reviewer_name": "Rahul Nair", "rating": 4.9, "text": "Extremely competitive entry but unmatched training for aspiring doctors."},
        ],
    },
    {
        "name": "Christian Medical College (CMC), Vellore",
        "location": "Vellore, Tamil Nadu",
        "fees": 350000,
        "rating": 4.8,
        "stream": "Medical",
        "institution_type": "College",
        "courses": "MBBS, B.Sc Nursing, MD Radiology, MS Orthopaedics, DM Neurology",
        "placements_pct": 97.5,
        "package_median": 10.5,
        "package_highest": 22.0,
        "logo_url": "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Christian_Medical_College_Vellore_logo.png/240px-Christian_Medical_College_Vellore_logo.png",
        "description": "CMC Vellore is a private medical college and hospital known for compassionate care, community health programs, and rigorous MBBS training since 1918.",
        "cutoffs": [
            {"exam": "NEET-UG", "branch": "MBBS", "category": "General", "min_rank": 100, "max_rank": 800},
            {"exam": "NEET-UG", "branch": "B.Sc Nursing", "category": "General", "min_rank": 5000, "max_rank": 25000},
        ],
        "reviews": [
            {"reviewer_name": "Meena Joseph", "rating": 4.8, "text": "Strong ethics-focused curriculum. Campus hospital handles diverse cases daily."},
            {"reviewer_name": "Arjun Pillai", "rating": 4.7, "text": "Fees are higher than government colleges but education quality is exceptional."},
        ],
    },
    {
        "name": "Maulana Azad Medical College (MAMC), New Delhi",
        "location": "New Delhi, Delhi",
        "fees": 15000,
        "rating": 4.7,
        "stream": "Medical",
        "institution_type": "College",
        "courses": "MBBS, MD Pathology, MD Pharmacology, MS ENT, MS Ophthalmology",
        "placements_pct": 96.0,
        "package_median": 9.0,
        "package_highest": 18.0,
        "logo_url": "https://upload.wikimedia.org/wikipedia/en/thumb/5/5e/Maulana_Azad_Medical_College_logo.png/240px-Maulana_Azad_Medical_College_logo.png",
        "description": "MAMC is a government medical college affiliated with the University of Delhi, attached to Lok Nayak Hospital. Highly sought after for affordable quality medical education.",
        "cutoffs": [
            {"exam": "NEET-UG", "branch": "MBBS", "category": "General", "min_rank": 80, "max_rank": 650},
            {"exam": "NEET-UG", "branch": "MBBS", "category": "EWS", "min_rank": 100, "max_rank": 900},
        ],
        "reviews": [
            {"reviewer_name": "Sana Khan", "rating": 4.6, "text": "Busy government hospital gives hands-on clinical practice. Great value for fees."},
            {"reviewer_name": "Vikram Singh", "rating": 4.5, "text": "Infrastructure is improving; faculty and patient load prepare you well for PG exams."},
        ],
    },
    {
        "name": "King George's Medical University (KGMU), Lucknow",
        "location": "Lucknow, Uttar Pradesh",
        "fees": 54000,
        "rating": 4.6,
        "stream": "Medical",
        "institution_type": "College",
        "courses": "MBBS, BDS, MD Anaesthesiology, MS Obstetrics & Gynaecology, MDS Oral Surgery",
        "placements_pct": 94.0,
        "package_median": 8.5,
        "package_highest": 16.0,
        "logo_url": "https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/King_George%27s_Medical_University_logo.png/240px-King_George%27s_Medical_University_logo.png",
        "description": "KGMU is one of North India's oldest medical universities, offering MBBS, BDS, and super-speciality programs with attached teaching hospitals.",
        "cutoffs": [
            {"exam": "NEET-UG", "branch": "MBBS", "category": "General", "min_rank": 400, "max_rank": 3500},
            {"exam": "NEET-UG", "branch": "BDS", "category": "General", "min_rank": 8000, "max_rank": 22000},
        ],
        "reviews": [
            {"reviewer_name": "Ayesha Rizvi", "rating": 4.5, "text": "Large campus and hospital network. Good for students targeting UP state health services."},
            {"reviewer_name": "Mohit Agarwal", "rating": 4.4, "text": "Affordable fees and solid NEET rank requirement. Dental wing is well regarded."},
        ],
    },
    # —— Schools (Senior Secondary) ——
    {
        "name": "Delhi Public School, R.K. Puram",
        "location": "New Delhi, Delhi",
        "fees": 185000,
        "rating": 4.8,
        "stream": "Science",
        "institution_type": "School",
        "courses": "Class XI-XII Science (PCM), Class XI-XII Science (PCB), Class XI-XII Commerce, Class XI-XII Humanities",
        "placements_pct": 98.0,
        "package_median": 0.0,
        "package_highest": 0.0,
        "logo_url": "https://upload.wikimedia.org/wikipedia/en/thumb/4/4f/Delhi_Public_School_logo.svg/240px-Delhi_Public_School_logo.svg.png",
        "description": "DPS R.K. Puram is among India's most prestigious CBSE schools. Known for Olympiad culture, IIT-JEE/NEET foundation programs, and strong alumni network in top universities.",
        "cutoffs": [
            {"exam": "CBSE Class X", "branch": "Science PCM", "category": "General", "min_rank": 90, "max_rank": 100},
            {"exam": "School Aptitude Test", "branch": "Science PCB", "category": "General", "min_rank": 85, "max_rank": 98},
            {"exam": "CBSE Class X", "branch": "Commerce", "category": "General", "min_rank": 88, "max_rank": 100},
        ],
        "reviews": [
            {"reviewer_name": "Isha Malhotra", "rating": 4.9, "text": "Excellent teachers and co-curricular balance. Science block labs are outstanding."},
            {"reviewer_name": "Parent — Mr. Gupta", "rating": 4.7, "text": "Competitive admission but worth it for board results and college counselling support."},
        ],
    },
    {
        "name": "The Mother's International School, New Delhi",
        "location": "New Delhi, Delhi",
        "fees": 120000,
        "rating": 4.7,
        "stream": "Science",
        "institution_type": "School",
        "courses": "Class XI-XII Science (PCM/PCB), Class XI-XII Commerce, Class XI-XII Arts",
        "placements_pct": 96.5,
        "package_median": 0.0,
        "package_highest": 0.0,
        "logo_url": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/The_Mother%27s_International_School_logo.png/240px-The_Mother%27s_International_School_logo.png",
        "description": "MIS is a reputed CBSE school in Sri Aurobindo Marg, Delhi, emphasizing holistic education, arts integration, and strong Class XII board performance.",
        "cutoffs": [
            {"exam": "CBSE Class X", "branch": "Science PCM", "category": "General", "min_rank": 88, "max_rank": 100},
            {"exam": "CBSE Class X", "branch": "Arts", "category": "General", "min_rank": 80, "max_rank": 95},
        ],
        "reviews": [
            {"reviewer_name": "Nandini Rao", "rating": 4.8, "text": "Supportive environment, less rote pressure than typical coaching-school culture."},
            {"reviewer_name": "Kabir Shah", "rating": 4.6, "text": "Great for students who want Science with room for music and debate societies."},
        ],
    },
    {
        "name": "St. Xavier's Collegiate School, Kolkata",
        "location": "Kolkata, West Bengal",
        "fees": 95000,
        "rating": 4.6,
        "stream": "Commerce",
        "institution_type": "School",
        "courses": "Class XI-XII Commerce, Class XI-XII Science (PCM), Class XI-XII Humanities",
        "placements_pct": 95.0,
        "package_median": 0.0,
        "package_highest": 0.0,
        "logo_url": "https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/St._Xavier%27s_Collegiate_School_logo.png/240px-St._Xavier%27s_Collegiate_School_logo.png",
        "description": "Founded in 1860, St. Xavier's Collegiate School is a landmark ICSE/CBSE institution in Kolkata with distinguished Commerce and Humanities streams.",
        "cutoffs": [
            {"exam": "ICSE Class X", "branch": "Commerce", "category": "General", "min_rank": 85, "max_rank": 100},
            {"exam": "ICSE Class X", "branch": "Science PCM", "category": "General", "min_rank": 90, "max_rank": 100},
        ],
        "reviews": [
            {"reviewer_name": "Debjani Sen", "rating": 4.7, "text": "Commerce faculty is excellent; many students clear CA Foundation alongside Class XII."},
            {"reviewer_name": "Rohan Das", "rating": 4.5, "text": "Historic campus and strong discipline. Great network for Kolkata university admissions."},
        ],
    },
    {
        "name": "La Martinière College, Lucknow",
        "location": "Lucknow, Uttar Pradesh",
        "fees": 110000,
        "rating": 4.5,
        "stream": "Arts",
        "institution_type": "School",
        "courses": "Class XI-XII Humanities, Class XI-XII Commerce, Class XI-XII Science (PCM)",
        "placements_pct": 92.0,
        "package_median": 0.0,
        "package_highest": 0.0,
        "logo_url": "https://upload.wikimedia.org/wikipedia/en/thumb/1/1e/La_Martiniere_Lucknow_logo.png/240px-La_Martiniere_Lucknow_logo.png",
        "description": "La Martinière Lucknow is a heritage ICSE school known for liberal arts, debating, and leadership programs. Offers balanced streams for university preparation.",
        "cutoffs": [
            {"exam": "ICSE Class X", "branch": "Humanities", "category": "General", "min_rank": 75, "max_rank": 95},
            {"exam": "ICSE Class X", "branch": "Commerce", "category": "General", "min_rank": 80, "max_rank": 98},
        ],
        "reviews": [
            {"reviewer_name": "Priya Awasthi", "rating": 4.6, "text": "Beautiful campus and strong arts/music programs. Humanities teachers are very engaging."},
            {"reviewer_name": "Aditya Khanna", "rating": 4.4, "text": "Good mix of academics and extracurriculars. Ideal for students leaning toward law and design."},
        ],
    },
    {
        "name": "Bishop Cotton Boys' School, Bengaluru",
        "location": "Bengaluru, Karnataka",
        "fees": 145000,
        "rating": 4.7,
        "stream": "Science",
        "institution_type": "School",
        "courses": "Class XI-XII Science (PCM/PCB), Class XI-XII Commerce, ISC Board",
        "placements_pct": 97.0,
        "package_median": 0.0,
        "package_highest": 0.0,
        "logo_url": "https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/Bishop_Cotton_Boys_School_logo.png/240px-Bishop_Cotton_Boys_School_logo.png",
        "description": "Bishop Cotton Boys' School is one of Bengaluru's oldest ICSE/ISC institutions, with rigorous Science programs and strong sports tradition.",
        "cutoffs": [
            {"exam": "ICSE Class X", "branch": "Science PCM", "category": "General", "min_rank": 88, "max_rank": 100},
            {"exam": "ISC Entrance", "branch": "Science PCB", "category": "General", "min_rank": 85, "max_rank": 98},
        ],
        "reviews": [
            {"reviewer_name": "Karthik Menon", "rating": 4.8, "text": "Top ISC scores in Karnataka. JEE/NEET prep support available through school tie-ups."},
            {"reviewer_name": "Parent — Mrs. Iyer", "rating": 4.6, "text": "Structured academics with excellent cricket and athletics facilities."},
        ],
    },
]
